In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import folium
import ckanapi as ck
import os
from dotenv import load_dotenv

#### API Key Loading
If you don't have an API key, get one here: https://api.data.gov/signup/

This block is just to load in your api key, in order to use it make a file titled '.env' like literally just that, no actual file name just '.env' and put this in there

API_KEY = [insert your api key here]

In [4]:
load_dotenv()
API_KEY = os.getenv('API_KEY')

#### Wrapper Function for Searching CKAN API
I wrote this function for searching the CKAN API since I think it's really annoying to do by hand. Honestly probably don't even need this function but I'm so fed up with the CKAN API that I have this now.

Note about the output of this function: It outputs a giant dictionary that's just a lot of JSON. To actually get the data instead of just more JSON metadata, look any dictionary that has a metadata tag about a **datastore being True** and then find the **package id** and thats how you get the actual data instead of more useless JSON metadata

In [119]:
#Initial CKAN request (I guess a lot of governments use CKAN for their open access data

def search_package(url,query):
    '''
    Queries the CKAN API and returns the results as a JSON Dictionary.

    Args:
        url: CKAN API URL
        query: Query string

    Returns:
        results: JSON Dictionary
    '''

    #Sidenote: I wrote the docstring myself using guidelines from https://www.geeksforgeeks.org/python/python-docstrings/
    #none of my code was written by AI lol
    request = ck.RemoteCKAN(url, apikey=API_KEY)
    result = request.call_action('package_search', {'q':query})
    return result

#### Finding the Actual Data
This entire code block is literally just looking for the actual data instead of the random JSON metadata. The final output of this cell, 'data_dicts' is literally just to display the name of the sub-dataset and the resource ID for it. You need the resource ID to call the actual data, NOT the package ID. The package ID will just spit out a bunch of random metadata no one cares about.

**Also really important note:** I'm actually using a different dataset here: https://data.chhs.ca.gov/dataset/hospital-inpatient-characteristics-by-patient-county-of-residence

The one we talked about using before was the dataset *by facility* meaning by hospital. We don't really need the hospital stuff since we don't really care about the hospital these cases were from, just the county. This dataset also splits all the data into separate files for sex, race, type of care, ect. which is why I made a dictionary to link 9 resource IDs as opposed to just one.

In [189]:
ca_hhs_url = 'https://data.chhs.ca.gov/'
inpatient_query = 'hospital inpatient characteristics - MDC by patient county'
#See above Markdown text to see how I got this ugly subsetting
#If you want to see what I had to look through to get the subsetting, just run the function without any of the bracket stuff
hospital_patient_json = search_package(ca_hhs_url, inpatient_query)['results'][0]['resources'][1:9]

#Making individual lists for the name of the Resource and the Resource ID
data_names = [dct['name'] for dct in hospital_patient_json]
data_ids = [dct['resource_id'] for dct in hospital_patient_json]

#Putting them into one dictionary and calling it
data_dicts = {data_names[i]:data_ids[i] for i in range(len(data_names))}
data_dicts

[{'accrual_periodicity': 'annually',
  'additional_information': '',
  'additional_limitations': '',
  'author': 'Department of Health Care Access and Information, Healthcare Analytics Branch',
  'author_email': None,
  'citation': '',
  'contact_email': 'dataandreports@hcai.ca.gov',
  'creator_user_id': 'fd826e35-dce7-4e6a-bf68-212389b73fc2',
  'data_collection_tool': 'Patient Data Reporting',
  'data_license': 'Terms of Use',
  'de_identification_method': 'https://chhsdata.github.io/dataplaybook/resource_library/#datade-id',
  'geo_coverage': 'Statewide',
  'geographic_granularity': 'location point',
  'id': 'ed5d21ce-9ec4-44ca-a482-2f4c767e0528',
  'isopen': False,
  'language': 'English',
  'license_id': None,
  'license_title': None,
  'limitations': 'Limitations',
  'maintainer': None,
  'maintainer_email': None,
  'metadata_created': '2018-03-14T17:40:29.530515',
  'metadata_modified': '2025-11-07T01:38:03.862887',
  'name': 'hospital-inpatient-characteristics-by-facility-pivot-profile',
  'notes': 'This dataset contains annual Excel pivot tables that display summaries of the inpatients treated in each hospital.  The summary data include discharges, discharge days, average length of stay, age groups, race groups, sex, expected payer, type of care, do not resuscitate orders, admission source, admission type, discharge disposition, principal diagnosis groups, principal procedure groups, and principal external cause of injury/morbidity groups.  The data can also be summarized statewide or for a specific hospital county, bed size grouping, and/or type of control.',
  'num_resources': 14,
  'num_tags': 23,
  'organization': {'id': 'c313a13b-c913-423c-8555-123e2b76cf20',
   'name': 'department-of-health-care-access-and-information',
   'title': 'Department of Health Care Access and Information',
   'type': 'organization',
   'description': 'Welcome to HCAI, formerly the Office of Statewide Health Planning and Development. HCAI is committed to expanding equitable access to health care for all Californians—ensuring every community has the health workforce they need, safe and reliable health care facilities, and health information that can help make care more effective and affordable. ',
   'image_url': '2024-10-21-222822.927967HCAIlogo.png',
   'created': '2017-05-25T19:53:24.795437',
   'is_organization': True,
   'approval_status': 'approved',
   'state': 'active'},
  'owner_org': 'c313a13b-c913-423c-8555-123e2b76cf20',
  'private': False,
  'program_web_page': 'https://www.hcai.ca.gov',
  'related_resources': '',
  'secondary_sources': '',
  'state': 'active',
  'temporal_coverage': '2012-most current year available',
  'title': 'Hospital Inpatient - Characteristics by Facility (Pivot Profile)',
  'twitter_popup': [],
  'type': 'dataset',
  'url': '',
  'version': None,
  'groups': [{'description': '',
    'display_name': 'Healthcare',
    'id': 'e47aee6b-d251-43a1-b665-be84e433f3d6',
    'image_display_url': 'https://data.chhs.ca.gov/uploads/group/2017-05-31-185537.653868care-1.svg',
    'name': 'healthcare',
    'title': 'Healthcare'}],
  'resources': [{'accept_popup': [],
    'cache_last_updated': None,
    'cache_url': None,
    'created': '2025-10-08T17:40:39.604844',
    'datastore_active': False,
    'datastore_contains_all_records_of_source_file': False,
    'description': 'This data table contains the annual Excel pivot table that displays summaries of the inpatients treated in each hospital. The summary data include discharges, discharge days, average length of stay, age groups, race groups, sex, expected payer, type of care, do not resuscitate orders, admission source, admission type, discharge disposition, principal diagnosis groups and principal procedure groups. The data can also be summarized statewide or for a specific hospital county, bed size grouping, and/or type of control.',
    'format': '.xlsx',
    'hash': '',
    'id': 'ee3e0896-9104-4a5b-811e-46b75f7e15d8',
    'last_modified': None,
    'metadata_modified': '2025-10-08T17:41:08.357526',
    'mimetype': None,
    'mimetype_inner': None,
    'name': '2024 Hospital Inpatient - Characteristics by Facility (Pivot Profile)',
    'package_id': 'ed5d21ce-9ec4-44ca-a482-2f4c767e0528',
    'position': 0,
    'resource_type': None,
    'size': 1724148,
    'state': 'active',
    'url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/ee3e0896-9104-4a5b-811e-46b75f7e15d8/download/2024pddpivot.xlsx',
    'url_type': 'upload'},
   {'accept_popup': [],
    'cache_last_updated': None,
    'cache_url': None,
    'created': '2024-10-01T13:13:53.905032',
    'datastore_active': False,
    'datastore_contains_all_records_of_source_file': False,
    'description': 'This data table contains the annual Excel pivot table that displays summaries of the inpatients treated in each hospital. The summary data include discharges, discharge days, average length of stay, age groups, race groups, sex, expected payer, type of care, do not resuscitate orders, admission source, admission type, discharge disposition, principal diagnosis groups and principal procedure groups. The data can also be summarized statewide or for a specific hospital county, bed size grouping, and/or type of control.',
    'format': 'XLSX',
    'hash': '',
    'id': '995b1051-480a-4992-bb10-108b996b9891',
    'last_modified': '2024-10-01T13:13:53.752466',
    'metadata_modified': '2024-10-01T13:14:22.504100',
    'mimetype': None,
    'mimetype_inner': None,
    'name': '2023 Hospital Inpatient - Characteristics by Facility (Pivot Profile)',
    'package_id': 'ed5d21ce-9ec4-44ca-a482-2f4c767e0528',
    'position': 1,
    'resource_type': None,
    'size': 1740830,
    'state': 'active',
    'url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/995b1051-480a-4992-bb10-108b996b9891/download/2023pddpivot.xlsx',
    'url_type': 'upload'},
   {'accept_popup': [],
    'cache_last_updated': None,
    'cache_url': None,
    'created': '2023-10-02T14:30:43.991739',
    'datastore_active': False,
    'datastore_contains_all_records_of_source_file': False,
    'description': 'This data table contains the annual Excel pivot table that displays summaries of the inpatients treated in each hospital. The summary data include discharges, discharge days, average length of stay, age groups, race groups, sex, expected payer, type of care, do not resuscitate orders, admission source, admission type, discharge disposition, principal diagnosis groups and principal procedure groups. The data can also be summarized statewide or for a specific hospital county, bed size grouping, and/or type of control.',
    'format': 'XLSX',
    'hash': '',
    'id': '7bacc638-e70a-4d02-ba25-18ea0874cea2',
    'last_modified': '2023-10-02T14:30:43.866845',
    'metadata_modified': '2023-10-02T14:31:15.930380',
    'mimetype': None,
    'mimetype_inner': None,
    'name': '2022 Hospital Inpatient - Characteristics by Facility (Pivot Profile)',
    'package_id': 'ed5d21ce-9ec4-44ca-a482-2f4c767e0528',
    'position': 2,
    'resource_type': None,
    'size': 1736990,
    'state': 'active',
    'url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/7bacc638-e70a-4d02-ba25-18ea0874cea2/download/2022pddpivot.xlsx',
    'url_type': 'upload'},
   {'accept_popup': [],
    'cache_last_updated': None,
    'cache_url': None,
    'ckan_url': 'https://data.chhs.ca.gov',
    'created': '2022-09-01T15:39:04.370538',
    'datastore_active': True,
    'datastore_contains_all_records_of_source_file': True,
    'description': 'This data table contains the annual Excel pivot table that displays summaries of the inpatients treated in each hospital. The summary data include discharges, discharge days, average length of stay, age groups, race groups, sex, expected payer, type of care, do not resuscitate orders, admission source, admission type, discharge disposition, principal diagnosis groups and principal procedure groups. The data can also be summarized statewide or for a specific hospital county, bed size grouping, and/or type of control.',
    'format': 'XLSX',
    'hash': '2fe184351b97ff15ad115812feee0de3',
    'id': '2d8dfcde-e81e-4968-8a80-6e7c550fbd59',
    'ignore_hash': 'False',
    'last_modified': '2022-09-01T15:39:04.236721',
    'metadata_modified': '2023-10-02T14:30:43.913804',
    'mimetype': None,
    'mimetype_inner': None,
    'name': '2021 Hospital Inpatient - Characteristics by Facility (Pivot Profile)',
    'original_url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/2d8dfcde-e81e-4968-8a80-6e7c550fbd59/download/2021pddpivot.xlsx',
    'package_id': 'ed5d21ce-9ec4-44ca-a482-2f4c767e0528',
    'position': 3,
    'resource_id': '2d8dfcde-e81e-4968-8a80-6e7c550fbd59',
    'resource_type': None,
    'set_url_type': 'False',
    'size': 1736211,
    'state': 'active',
    'task_created': '2022-09-01 15:39:05.004085',
    'url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/2d8dfcde-e81e-4968-8a80-6e7c550fbd59/download/2021pddpivot.xlsx',
    'url_type': 'upload'},
   {'accept_popup': [],
    'cache_last_updated': None,
    'cache_url': None,
    'ckan_url': 'https://data.chhs.ca.gov',
    'created': '2021-08-02T14:15:01.249815',
    'datastore_active': True,
    'datastore_contains_all_records_of_source_file': True,
    'description': 'This data table contains the annual Excel pivot table that displays summaries of the inpatients treated in each hospital. The summary data include discharges, discharge days, average length of stay, age groups, race groups, sex, expected payer, type of care, do not resuscitate orders, admission source, admission type, discharge disposition, principal diagnosis groups and principal procedure groups. The data can also be summarized statewide or for a specific hospital county, bed size grouping, and/or type of control.',
    'format': 'XLSX',
    'hash': 'e59eec0f5e030f00782a21a540da7533',
    'id': 'fad0810c-4d37-445b-b7fd-dbb593ab7203',
    'ignore_hash': 'False',
    'last_modified': '2021-08-02T14:15:01.137952',
    'metadata_modified': '2023-10-02T14:30:43.913946',
    'mimetype': None,
    'mimetype_inner': None,
    'name': '2020 Hospital Inpatient - Characteristics by Facility (Pivot Profile)',
    'original_url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/fad0810c-4d37-445b-b7fd-dbb593ab7203/download/2020pddpivot.xlsx',
    'package_id': 'ed5d21ce-9ec4-44ca-a482-2f4c767e0528',
    'position': 4,
    'resource_id': 'fad0810c-4d37-445b-b7fd-dbb593ab7203',
    'resource_type': None,
    'set_url_type': 'False',
    'size': 1730937,
    'state': 'active',
    'task_created': '2021-08-02 14:15:01.989773',
    'url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/fad0810c-4d37-445b-b7fd-dbb593ab7203/download/2020pddpivot.xlsx',
    'url_type': 'upload'},
   {'accept_popup': [],
    'cache_last_updated': None,
    'cache_url': None,
    'ckan_url': 'https://data.chhs.ca.gov',
    'created': '2020-10-01T13:12:16.776127',
    'datastore_active': True,
    'datastore_contains_all_records_of_source_file': True,
    'description': 'This data table contains the annual Excel pivot table that displays summaries of the inpatients treated in each hospital. The summary data include discharges, discharge days, average length of stay, age groups, race groups, sex, expected payer, type of care, do not resuscitate orders, admission source, admission type, discharge disposition, principal diagnosis groups and principal procedure groups. The data can also be summarized statewide or for a specific hospital county, bed size grouping, and/or type of control.',
    'format': 'XLSX',
    'hash': 'd4d2970dac3ad6bfe006b077c93229b4',
    'id': 'e335b3d8-b3cc-42f3-b354-8157779c006a',
    'ignore_hash': 'False',
    'last_modified': '2020-10-01T17:27:31.258931',
    'metadata_modified': '2023-10-02T14:30:43.914056',
    'mimetype': None,
    'mimetype_inner': None,
    'name': '2019 Hospital Inpatient - Characteristics by Facility (Pivot Profile)',
    'original_url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/e335b3d8-b3cc-42f3-b354-8157779c006a/download/2019pddpivot.xlsx',
    'package_id': 'ed5d21ce-9ec4-44ca-a482-2f4c767e0528',
    'position': 5,
    'resource_id': 'e335b3d8-b3cc-42f3-b354-8157779c006a',
    'resource_type': None,
    'set_url_type': 'False',
    'size': 1762190,
    'state': 'active',
    'task_created': '2021-08-02 14:15:02.437889',
    'url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/e335b3d8-b3cc-42f3-b354-8157779c006a/download/2019pddpivot.xlsx',
    'url_type': 'upload'},
   {'accept_popup': [],
    'cache_last_updated': None,
    'cache_url': None,
    'ckan_url': 'https://data.chhs.ca.gov',
    'created': '2019-08-01T13:54:41.539884',
    'datastore_active': True,
    'datastore_contains_all_records_of_source_file': True,
    'description': 'This data table contains the annual Excel pivot table that displays summaries of the inpatients treated in each hospital. The summary data include discharges, discharge days, average length of stay, age groups, race groups, sex, expected payer, type of care, do not resuscitate orders, admission source, admission type, discharge disposition, principal diagnosis groups, principal procedure groups, and principal external cause of injury/morbidity groups. The data can also be summarized statewide or for a specific hospital county, bed size grouping, and/or type of control.',
    'format': 'XLSX',
    'hash': 'f1ffc0a35c724a717a0a08b4e4a1fb52',
    'id': '5de5dbdc-aebf-4104-92e3-d52253e47799',
    'ignore_hash': 'False',
    'last_modified': '2019-08-01T13:54:41.408183',
    'metadata_modified': '2023-10-02T14:30:43.914162',
    'mimetype': None,
    'mimetype_inner': None,
    'name': '2018 Hospital Inpatient - Characteristics by Facility (Pivot Profile)',
    'original_url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/5de5dbdc-aebf-4104-92e3-d52253e47799/download/2018pddpivot.xlsx',
    'package_id': 'ed5d21ce-9ec4-44ca-a482-2f4c767e0528',
    'position': 6,
    'resource_id': '5de5dbdc-aebf-4104-92e3-d52253e47799',
    'resource_type': None,
    'set_url_type': 'False',
    'size': 1778842,
    'state': 'active',
    'task_created': '2021-08-02 14:15:02.373955',
    'url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/5de5dbdc-aebf-4104-92e3-d52253e47799/download/2018pddpivot.xlsx',
    'url_type': 'upload'},
   {'accept_popup': [],
    'cache_last_updated': None,
    'cache_url': None,
    'ckan_url': 'https://data.chhs.ca.gov',
    'created': '2018-07-18T18:11:43.389513',
    'datastore_active': True,
    'datastore_contains_all_records_of_source_file': True,
    'description': 'This data table contains the annual Excel pivot table that displays summaries of the inpatients treated in each hospital.  The summary data include discharges, discharge days, average length of stay, age groups, race groups, sex, expected payer, type of care, do not resuscitate orders, admission source, admission type, discharge disposition, principal diagnosis groups, principal procedure groups, and principal external cause of injury/morbidity groups.  The data can also be summarized statewide or for a specific hospital county, bed size grouping, and/or type of control.',
    'format': 'XLSX',
    'hash': '0220010bc100bda86aeb02596a31e3f4',
    'id': 'fa44b3f7-7c0d-4baa-b49c-4ebb8c4ebe4e',
    'ignore_hash': 'False',
    'last_modified': '2018-07-18T18:11:43.299615',
    'metadata_modified': '2023-10-02T14:30:43.914264',
    'mimetype': None,
    'mimetype_inner': None,
    'name': '2017 Hospital Inpatient - Characteristics by Facility (Pivot Profile)',
    'original_url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/fa44b3f7-7c0d-4baa-b49c-4ebb8c4ebe4e/download/2017pddpivot20180712.xlsm',
    'package_id': 'ed5d21ce-9ec4-44ca-a482-2f4c767e0528',
    'position': 7,
    'resource_id': 'fa44b3f7-7c0d-4baa-b49c-4ebb8c4ebe4e',
    'resource_type': None,
    'set_url_type': 'False',
    'size': None,
    'state': 'active',
    'task_created': '2021-08-02 14:15:02.124677',
    'url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/fa44b3f7-7c0d-4baa-b49c-4ebb8c4ebe4e/download/2017pddpivot20180712.xlsm',
    'url_type': 'upload'},
   {'accept_popup': [],
    'cache_last_updated': None,
    'cache_url': None,
    'ckan_url': 'https://data.chhs.ca.gov',
    'created': '2018-03-14T17:45:26.000116',
    'datastore_active': True,
    'datastore_contains_all_records_of_source_file': True,
    'description': 'This data table contains the annual Excel pivot table that displays summaries of the inpatients treated in each hospital.  The summary data include discharges, discharge days, average length of stay, age groups, race groups, sex, expected payer, type of care, do not resuscitate orders, admission source, admission type, discharge disposition, principal diagnosis groups, principal procedure groups, and principal external cause of injury/morbidity groups.  The data can also be summarized statewide or for a specific hospital county, bed size grouping, and/or type of control.',
    'format': 'XLSX',
    'hash': 'dc75d86bbb2b7345c0bcde00d2e927d0',
    'id': 'd99abb19-5de1-486a-bfae-351dc76955da',
    'ignore_hash': 'False',
    'last_modified': '2018-03-14T17:45:25.916652',
    'metadata_modified': '2023-10-02T14:30:43.914365',
    'mimetype': None,
    'mimetype_inner': None,
    'name': '2016 Hospital Inpatient - Characteristics by Facility (Pivot Profile)',
    'original_url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/d99abb19-5de1-486a-bfae-351dc76955da/download/2016-patient-discharge-data-pivot.xlsm',
    'package_id': 'ed5d21ce-9ec4-44ca-a482-2f4c767e0528',
    'position': 8,
    'resource_id': 'd99abb19-5de1-486a-bfae-351dc76955da',
    'resource_type': None,
    'set_url_type': 'False',
    'size': None,
    'state': 'active',
    'task_created': '2021-08-02 14:15:02.063191',
    'url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/d99abb19-5de1-486a-bfae-351dc76955da/download/2016-patient-discharge-data-pivot.xlsm',
    'url_type': 'upload'},
   {'accept_popup': [],
    'cache_last_updated': None,
    'cache_url': None,
    'ckan_url': 'https://data.chhs.ca.gov',
    'created': '2018-03-14T17:44:29.164480',
    'datastore_active': True,
    'datastore_contains_all_records_of_source_file': True,
    'description': 'This data table contains the annual Excel pivot table that displays summaries of the inpatients treated in each hospital.  The summary data include discharges, discharge days, average length of stay, age groups, race groups, sex, expected payer, type of care, do not resuscitate orders, admission source, admission type, discharge disposition, principal diagnosis groups, principal procedure groups, and principal external cause of injury/morbidity groups.  The data can also be summarized statewide or for a specific hospital county, bed size grouping, and/or type of control.',
    'format': 'XLSX',
    'hash': 'c9dea43e17cb1d394649f141fa853428',
    'id': '94ee6a83-bcb3-4568-ad93-062fb7bdd254',
    'ignore_hash': 'False',
    'last_modified': '2018-03-14T17:44:29.079687',
    'metadata_modified': '2023-10-02T14:30:43.914465',
    'mimetype': None,
    'mimetype_inner': None,
    'name': '2015 Hospital Inpatient - Characteristics by Facility (Pivot Profile)',
    'original_url': 'https://data.chhs.ca.gov/dataset/ed5d21ce-9ec4-44ca-a482-2f4c767e0528/resource/94ee6a83-bcb3-4568-ad93-062fb7bdd254/download/2015-patient-discharge-data-pivot.xlsx',

#### Actually Getting the Data Now
This tiny code block actually pulls the data from the API as opposed to just looking for the information to locate the data. Basically the previous code block was just getting the resource IDs for the stuff we want and this one actually gets the stuff we want. As for the "stuff we want" I just kinda grabbed a few that seem useful, but can add more if needed. Is this making a lot of API calls? Yeah kinda. Do we need to make them more than once ever? No so it should be fine I hope lol.

In [122]:
data_request = ck.RemoteCKAN('https://data.chhs.ca.gov/', apikey=API_KEY)
MDC_data_dict = data_request.call_action('datastore_search', {'resource_id':'57eaaf0f-6ba9-428a-9498-07070c1e55cc',
                                              'limit':32000})
sex_data_dict = data_request.call_action('datastore_search', {'resource_id':'a9eaf75d-f45f-48f1-80d6-493eef9e7968',
                                              'limit':32000})
race_data_dict = data_request.call_action('datastore_search', {'resource_id':'83a8cd12-434a-4a8d-9721-ca75899568bd',
                                              'limit':32000})
care_data_dict = data_request.call_action('datastore_search', {'resource_id':'58bed582-14ae-4521-b43f-e7682edb0819',
                                              'limit':32000})

#### Pandas Data Cleanup
Just a bunch of pandas data cleaning, not really important to look at tbh but if you want it explained later just lmk

In [190]:
def inpatient_data_cleanup(dct, year, drops = None, renames=None):
    '''
    Takes a dict of JSON data and converts it into a pandas dataframe, dropping list specified columns and renaming columns specified by rename_key_dict.

    Parameters:
        dct: Dict of JSON data
        drops: Optional list of column names to drop
        renames: Optional dict of column names to rename
        year

    Returns:
        Pandas dataframe
    '''

    df = pd.DataFrame(dct['records'])

    if drops is not None and type(drops) is list:
        df = df.drop(columns= drops)
    elif drops is not None and type(drops) is not list:
        raise TypeError('drops must be a list')

    if type(renames) is dict and renames is not None:
        df = df.rename(columns=renames)
    elif type(renames) != dict and renames is not None:
        raise TypeError('renames must be a dictionary or use string "inpatient_default" for inpatient data default!')


    if (year >= 2012 or year <= 2024) and type(year) is int:
        if (renames == 'default' or type(renames) is dict):
            df['Year'] = df['Year'].apply(pd.to_numeric)
            df = df[df['Year'] == year]
        else:
            df['dsch_yr'] = df['dsch_yr'].apply(pd.to_numeric)
            df = df[df['dsch_yr'] == year]
    elif type(year) is not int:
        raise TypeError('year must be an integer!')
    elif year < 2012 or year > 2024:
        raise ValueError('year must be between 2012 and 2024!')

    return df

In [181]:
MDC_data = inpatient_data_cleanup(MDC_data_dict, 2024, ['AnnotationCode','AnnotationDesc','_id','mdc'], {'mdc_desc':'MDC'})
MDC_data[(MDC_data['MDC'] == 'NERVOUS SYSTEM, DISEASES & DISORDERS') |
         (MDC_data['MDC'] == 'RESPIRATORY SYSTEM, DISEASES & DISORDERS') |
         (MDC_data['MDC'] == 'CIRCULATORY SYSTEM, DISEASES & DISORDERS') |
         (MDC_data['MDC'] == 'DIGESTIVE SYSTEM, DISEASES & DISORDERS')]

        County  Year                                       MDC Discharges
312    Alameda  2024      NERVOUS SYSTEM, DISEASES & DISORDERS       9125
315    Alameda  2024  RESPIRATORY SYSTEM, DISEASES & DISORDERS       9254
316    Alameda  2024  CIRCULATORY SYSTEM, DISEASES & DISORDERS      13941
317    Alameda  2024    DIGESTIVE SYSTEM, DISEASES & DISORDERS       8593
474     Alpine  2024      NERVOUS SYSTEM, DISEASES & DISORDERS          4
...        ...   ...                                       ...        ...
18928     Yolo  2024    DIGESTIVE SYSTEM, DISEASES & DISORDERS       1247
19252     Yuba  2024      NERVOUS SYSTEM, DISEASES & DISORDERS        629
19255     Yuba  2024  RESPIRATORY SYSTEM, DISEASES & DISORDERS        660
19256     Yuba  2024  CIRCULATORY SYSTEM, DISEASES & DISORDERS       1143
19257     Yuba  2024    DIGESTIVE SYSTEM, DISEASES & DISORDERS        586

[239 rows x 4 columns]

In [182]:
sex_data = inpatient_data_cleanup(sex_data_dict, 2024, ['AnnotationCode','AnnotationDesc','_id'], renames = 'inpatient_default')
sex_data

       County  Year               Sex Discharges
36    Alameda  2024            Female      71064
37    Alameda  2024              Male      56894
38    Alameda  2024  Unknown, Invalid         27
63     Alpine  2024            Female       None
64     Alpine  2024              Male       None
...       ...   ...               ...        ...
1981     Yolo  2024              Male       7633
1982     Yolo  2024  Unknown, Invalid          4
2010     Yuba  2024            Female       5368
2011     Yuba  2024              Male       4073
2012     Yuba  2024  Unknown, Invalid          1

[160 rows x 4 columns]

In [183]:
race_data = inpatient_data_cleanup(race_data_dict, 2024, ['AnnotationCode','AnnotationDesc','_id'], {'race_grp1':'Race'})
race_data

       County  Year                                    Race Discharges
99    Alameda  2024           American Indian/Alaska Native        269
100   Alameda  2024                                   Asian      28727
101   Alameda  2024                                   Black      22319
102   Alameda  2024                                Hispanic      27218
103   Alameda  2024                           Invalid/Blank         10
...       ...   ...                                     ...        ...
6105     Yuba  2024                            Multi-racial         81
6106     Yuba  2024  Native Hawaiian/Other Pacific Islander         52
6107     Yuba  2024                                   Other        339
6108     Yuba  2024                                 Unknown        127
6109     Yuba  2024                                   White       5724

[546 rows x 4 columns]

In [184]:
care_data = inpatient_data_cleanup(care_data_dict, 2024, ['_id'], {'typcare1':'Care'})
care_data

       County  Year                               Care Discharges
64    Alameda  2024                         Acute Care     120153
65    Alameda  2024  Chemical Dependency Recovery Care         85
66    Alameda  2024                      Invalid/Blank         14
67    Alameda  2024       Physical Rehabilitation Care       1375
68    Alameda  2024                   Psychiatric Care       5740
...       ...   ...                                ...        ...
3855     Yuba  2024                         Acute Care       8873
3856     Yuba  2024  Chemical Dependency Recovery Care          2
3857     Yuba  2024       Physical Rehabilitation Care         93
3858     Yuba  2024                   Psychiatric Care        424
3859     Yuba  2024  Skilled Nursing/Intermediate Care         50

[295 rows x 4 columns]

#### Issue

Big problem now: I think all of the api stuff I just did was completely pointless. I used the other dataset (by county instead of by facility) because it has an api endpoint, unlike the facility one, except it only has *discharge* data, not data on the actual occupancy and doesn't include deaths. The facility one has all that data and even more but it doesn't have an API endpoint. In the next code block I'll clean up the excel data from the facility data but import it into python by just downloading the excel file.

Note: The facility data does actually have an api endpoint, but its all from 2021 or before, meaning we either have to choose to use very outdated data or use data heavily biased by the COVID-19 pandemic.

In [217]:
facility_data = pd.read_excel('./data/2024pddpivot.xlsx', sheet_name='Data')
facility_data = facility_data.filter(items = ['COUNTY',"Sex_Male", 'Sex_Female', 'Sex_Other_Unknown', 'Age_0_09', 'Age_10_19' 'Age_20_29', 'Age_30_39', 'Age_40_49', 'Age_50_59', 'Age_60_69', 'Age_70_79', 'Age_80_89', 'Age_Other_Unknown', 'eth_Hispanic', 'eth_Nonhispanic', 'eth_Other', 'racegrp_aman', 'racegrp_asian', 'racegrp_nhpi', 'racegrp_black', 'racegrp_white', 'racegrp_unknown', 'racegrp_other', 'racegrp_multirace', 'dx_Infectious', 'dx_Circulatory', 'dx_Respiratory', 'dx_Digestive', 'dx_Infectious', 'dx_Skin', 'dx_MentalHealth'])
for var in list(facility_data.columns)[1:len(facility_data.columns)]:
    facility_data[var] = facility_data[var].apply(pd.to_numeric)
    facility_data[var] = facility_data.groupby('COUNTY')[var].transform('sum')
facility_data = facility_data.drop_duplicates()
#need to fix ages
facility_data

C:\Users\Zachary\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,COUNTY,Sex_Male,Sex_Female,Sex_Other_Unknown,Age_0_09,Age_30_39,Age_40_49,Age_50_59,Age_60_69,Age_70_79,...,racegrp_white,racegrp_unknown,racegrp_other,racegrp_multirace,dx_Infectious,dx_Circulatory,dx_Respiratory,dx_Digestive,dx_Skin,dx_MentalHealth
0,ALAMEDA,63652,77486,36.0,21775.0,18809.0,10601.0,12349.0,18971.0,20076.0,...,43103.0,2443.0,37004.0,2680.0,16134.0,16297.0,7943.0,11238.0,1816.0,13707.0
18,AMADOR,1187,1372,0.0,220.0,178.0,118.0,203.0,465.0,574.0,...,2271.0,55.0,108.0,50.0,648.0,339.0,169.0,239.0,39.0,48.0
19,BUTTE,15440,17791,0.0,2735.0,3092.0,2630.0,3641.0,6283.0,6413.0,...,25757.0,469.0,4374.0,302.0,5439.0,4635.0,1933.0,3393.0,490.0,1122.0
23,CALAVERAS,430,486,0.0,0.0,42.0,61.0,99.0,211.0,232.0,...,864.0,17.0,21.0,0.0,113.0,130.0,132.0,146.0,43.0,41.0
24,COLUSA,355,358,0.0,0.0,55.0,53.0,128.0,160.0,141.0,...,627.0,3.0,0.0,41.0,176.0,98.0,86.0,60.0,38.0,27.0
25,CONTRA COSTA,35763,47551,9.0,11232.0,10461.0,5573.0,7337.0,11884.0,13802.0,...,43722.0,1835.0,15411.0,2028.0,9553.0,10926.0,4499.0,8030.0,1284.0,4920.0
33,DEL NORTE,1062,1237,0.0,263.0,200.0,168.0,237.0,423.0,432.0,...,1865.0,36.0,140.0,57.0,522.0,268.0,114.0,222.0,56.0,48.0
34,EL DORADO,3239,3712,0.0,682.0,736.0,530.0,612.0,1148.0,1358.0,...,5867.0,247.0,593.0,66.0,748.0,803.0,628.0,831.0,161.0,527.0
37,FRESNO,49784,64353,2.0,16045.0,15198.0,10287.0,12132.0,16635.0,15993.0,...,87692.0,752.0,7721.0,732.0,8822.0,14117.0,5660.0,10087.0,1797.0,5211.0
47,GLENN,162,175,0.0,0.0,12.0,13.0,27.0,66.0,105.0,...,294.0,20.0,23.0,0.0,24.0,19.0,60.0,17.0,15.0,2.0
48,HUMBOLDT,4830,5448,3.0,1096.0,1116.0,756.0,892.0,1756.0,2098.0,...,7936.0,525.0,725.0,174.0,1483.0,1435.0,639.0,1016.0,211.0,544.0
53,IMPERIAL,4542,6439,0.0,2387.0,1377.0,649.0,817.0,1464.0,1415.0,...,8932.0,118.0,1690.0,35.0,1328.0,931.0,707.0,1056.0,154.0,70.0
55,INYO,459,702,0.0,255.0,143.0,58.0,76.0,124.0,174.0,...,812.0,92.0,84.0,33.0,135.0,72.0,107.0,84.0,17.0,21.0
57,KERN,35590,43536,5.0,11951.0,10831.0,7123.0,8080.0,10910.0,9918.0,...,58501.0,1791.0,10738.0,203.0,8016.0,8805.0,4159.0,6547.0,1224.0,7458.0
70,KINGS,4759,7006,0.0,2294.0,1605.0,921.0,1152.0,1496.0,1321.0,...,9746.0,316.0,912.0,21.0,1439.0,938.0,502.0,1278.0,66.0,125.0
71,LAKE,1523,2020,0.0,406.0,310.0,230.0,363.0,645.0,731.0,...,2707.0,46.0,484.0,67.0,645.0,389.0,283.0,374.0,76.0,69.0
73,LASSEN,349,574,0.0,219.0,119.0,30.0,52.0,89.0,120.0,...,778.0,18.0,74.0,0.0,77.0,51.0,125.0,78.0,20.0,6.0
74,LOS ANGELES,476583,543871,160.0,121453.0,129101.0,90114.0,111674.0,155720.0,150862.0,...,459087.0,22857.0,296464.0,17912.0,105489.0,127983.0,55360.0,97215.0,14202.0,87153.0
180,MADERA,6191,4899,0.0,6413.0,367.0,267.0,144.0,68.0,13.0,...,7740.0,1480.0,412.0,395.0,370.0,137.0,2358.0,1164.0,181.0,1563.0
182,MARIN,9275,9725,4.0,1503.0,1585.0,1132.0,1621.0,2744.0,4263.0,...,14903.0,366.0,1713.0,393.0,2714.0,3056.0,1098.0,1926.0,304.0,868.0
186,MARIPOSA,182,228,0.0,0.0,24.0,21.0,45.0,82.0,91.0,...,317.0,70.0,0.0,0.0,49.0,62.0,61.0,46.0,22.0,11.0
187,MENDOCINO,2599,3328,1.0,743.0,541.0,366.0,512.0,980.0,1170.0,...,4265.0,169.0,1121.0,0.0,909.0,620.0,397.0,599.0,109.0,123.0
190,MERCED,6389,9456,1.0,2886.0,2198.0,1241.0,1464.0,2111.0,1879.0,...,11361.0,361.0,2031.0,109.0,1906.0,1443.0,788.0,1169.0,268.0,656.0
193,MODOC,145,224,0.0,0.0,0.0,16.0,18.0,54.0,100.0,...,323.0,17.0,29.0,0.0,52.0,45.0,83.0,18.0,16.0,4.0
195,MONO,260,178,0.0,27.0,43.0,60.0,59.0,82.0,83.0,...,375.0,7.0,32.0,0.0,9.0,24.0,47.0,48.0,10.0,14.0
196,MONTEREY,17815,21828,12.0,5526.0,4633.0,3007.0,3561.0,5352.0,6462.0,...,25201.0,364.0,10007.0,498.0,3723.0,5113.0,2290.0,4049.0,659.0,1974.0
201,NAPA,5191,5146,0.0,767.0,1065.0,735.0,1087.0,1717.0,2223.0,...,7311.0,349.0,1960.0,138.0,1115.0,2324.0,551.0,714.0,142.0,927.0
203,NEVADA,3043,3711,0.0,753.0,713.0,376.0,533.0,1079.0,1441.0,...,6232.0,203.0,196.0,22.0,1061.0,722.0,456.0,665.0,114.0,185.0
205,ORANGE,135708,163387,25.0,44460.0,38085.0,21952.0,27748.0,39997.0,43740.0,...,169297.0,7952.0,59644.0,6769.0,31454.0,33366.0,16498.0,27470.0,4067.0,20582.0
238,PLACER,26930,37407,6.0,10559.0,8323.0,4061.0,5088.0,8465.0,10679.0,...,45006.0,1894.0,7341.0,1204.0,8319.0,8008.0,3291.0,6479.0,971.0,1074.0
242,PLUMAS,222,217,0.0,0.0,18.0,20.0,25.0,80.0,123.0,...,408.0,31.0,0.0,0.0,15.0,44.0,68.0,48.0,29.0,15.0
245,RIVERSIDE,96836,111282,44.0,23783.0,25800.0,17513.0,22148.0,33188.0,32313.0,...,132787.0,4531.0,39469.0,6008.0,20652.0,28701.0,10513.0,20956.0,2803.0,13607.0
268,SACRAMENTO,81373,93036,19.0,22382.0,21004.0,14831.0,18283.0,28015.0,26859.0,...,88179.0,4218.0,34786.0,3602.0,17247.0,26556.0,10155.0,14023.0,2465.0,16611.0
288,SAN BENITO,953,1606,0.0,425.0,334.0,168.0,185.0,265.0,327.0,...,1077.0,23.0,1413.0,0.0,318.0,201.0,158.0,326.0,37.0,53.0
289,SAN BERNARDINO,103405,123024,8.0,32804.0,28989.0,21068.0,24948.0,33893.0,28355.0,...,110520.0,4117.0,69469.0,5606.0,20975.0,27859.0,14831.0,22497.0,3541.0,20843.0
312,SAN DIEGO,151620,180476,72.0,49453.0,42027.0,25090.0,31841.0,47119.0,48984.0,...,186366.0,9049.0,80962.0,7690.0,29167.0,41101.0,18677.0,31325.0,5157.0,22414.0
338,SAN FRANCISCO,53261,55590,17.0,13391.0,14782.0,9799.0,11470.0,17155.0,17138.0,...,46848.0,2687.0,20574.0,3337.0,8735.0,13720.0,4863.0,9823.0,2267.0,4869.0
350,SAN JOAQUIN,31818,39933,8.0,11220.0,8914.0,5436.0,7199.0,10800.0,10880.0,...,32299.0,1511.0,18700.0,2555.0,10726.0,8946.0,3710.0,6211.0,823.0,2209.0
360,SAN LUIS OBISPO,9000,10458,1.0,2647.0,2146.0,1251.0,1518.0,2710.0,3692.0,...,15398.0,1501.0,1636.0,239.0,2122.0,2538.0,1134.0,1976.0,227.0,923.0
365,SAN MATEO,18820,23025,4.0,4742.0,5364.0,2723.0,3482.0,5792.0,7515.0,...,20054.0,1144.0,5818.0,465.0,5507.0,6811.0,1908.0,3709.0,554.0,2368.0
372,SANTA BARBARA,17988,23228,7.0,6522.0,4505.0,2585.0,3147.0,5141.0,6798.0,...,30735.0,1287.0,6851.0,489.0,3839.0,4772.0,2099.0,3953.0,463.0,1583.0
378,SANTA CLARA,86554,103917,41.0,31668.0,25872.0,14212.0,17716.0,25135.0,26329.0,...,83436.0,3529.0,44443.0,4051.0,17680.0,23943.0,9698.0,17054.0,2358.0,8178.0
392,SANTA CRUZ,8101,9288,0.0,2302.0,2027.0,1242.0,1561.0,2410.0,3343.0,...,10162.0,727.0,5705.0,215.0,2405.0,2223.0,849.0,1699.0,318.0,816.0
396,SHASTA,10730,11831,2.0,1787.0,1848.0,1591.0,2337.0,4175.0,4866.0,...,19039.0,691.0,1235.0,309.0,2972.0,3800.0,1562.0,2265.0,407.0,925.0
402,SISKIYOU,943,1190,0.0,299.0,184.0,128.0,177.0,352.0,362.0,...,1740.0,105.0,104.0,39.0,270.0,236.0,232.0,178.0,46.0,30.0
404,SOLANO,15708,19454,7.0,4228.0,4294.0,2625.0,3389.0,5413.0,5797.0,...,17653.0,319.0,6100.0,793.0,4742.0,4732.0,1712.0,2939.0,508.0,2943.0
410,SONOMA,19261,22837,2.0,4811.0,4775.0,2886.0,3613.0,6195.0,7776.0,...,30457.0,1181.0,6611.0,801.0,5081.0,5183.0,2141.0,4184.0,643.0,4353.0
419,STANISLAUS,28292,33662,3.0,6806.0,6805.0,5357.0,6984.0,10271.0,10010.0,...,42670.0,2722.0,9963.0,416.0,6501.0,9548.0,3574.0,6423.0,873.0,3820.0
427,SUTTER,426,487,0.0,0.0,175.0,175.0,144.0,86.0,78.0,...,596.0,114.0,145.0,12.0,2.0,1.0,0.0,58.0,5.0,639.0
431,TEHAMA,1604,2250,0.0,523.0,437.0,276.0,322.0,544.0,551.0,...,3037.0,74.0,548.0,40.0,671.0,347.0,282.0,238.0,63.0,483.0
433,TRINITY,109,102,0.0,0.0,0.0,0.0,13.0,43.0,79.0,...,195.0,16.0,0.0,0.0,9.0,11.0,63.0,7.0,12.0,0.0
434,TULARE,15610,20503,7.0,6467.0,4390.0,2702.0,3541.0,4980.0,4790.0,...,28413.0,220.0,5296.0,219.0,1962.0,4453.0,2345.0,2938.0,502.0,1767.0
437,TUOLUMNE,2043,2503,1.0,482.0,355.0,223.0,328.0,881.0,1016.0,...,4146.0,163.0,161.0,0.0,908.0,617.0,288.0,404.0,71.0,85.0
438,VENTURA,32205,40432,18.0,8997.0,8091.0,5039.0,6746.0,10104.0,12174.0,...,53528.0,932.0,11527.0,1801.0,7734.0,9991.0,3846.0,7363.0,916.0,3263.0
446,YOLO,4207,6468,3.0,1872.0,1722.0,822.0,832.0,1383.0,1277.0,...,5701.0,639.0,2856.0,129.0,1457.0,717.0,362.0,903.0,109.0,1514.0
448,YUBA,5491,7319,2.0,1874.0,1313.0,925.0,1245.0,2136.0,2002.0,...,8348.0,147.0,2380.0,0.0,1851.0,2083.0,689.0,946.0,171.0,146.0