In [24]:
from asyncio.windows_events import NULL

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import python_cimis
import seaborn as sns
import folium
from folium.plugins import GroupedLayerControl
from fontTools.cu2qu.cu2qu import NAN
from fsspec.utils import infer_compression
import requests

In [ ]:
!pip install python_cimis
!pip install folium

In [36]:
age_vfever = pd.read_excel('ValleyFeverDashboard_Data.xlsx', sheet_name = 'Cases_Rates by Age Group').drop([0])
age_vfever.columns = ['AgeGroup','YearOnset','Cases','Rate']
monthly_vfever = pd.read_excel('ValleyFeverDashboard_Data.xlsx', sheet_name = 'Cases by Month').drop([0])
monthly_vfever.columns = ['Month', 'Year', 'Cases']
eth_vfever = pd.read_excel('ValleyFeverDashboard_Data.xlsx', sheet_name = 'Case % by Race_Ethnicity').drop([0])
eth_vfever.columns = ['Race/Ethnicity', 'California_Pop_Percent', 'Case_Percent']

vf = monthly_vfever
vf

    Month  Year Cases
1       1  2001    78
2       1  2002   139
3       1  2003   112
4       1  2004   251
5       1  2005   189
..    ...   ...   ...
284    12  2020   655
285    12  2021   654
286    12  2022   605
287    12  2023  1445
288    12  2024  1356

[288 rows x 3 columns]

In [70]:
# get data only from 2013
df_2013 = vf[vf["Year"] == 2013]

monthly_cases = df_2013.groupby("Month")["Cases"].sum()

# obtain percentages
total_cases = monthly_cases.sum()
percentages = (monthly_counts / total_cases) * 100

# building datafram with month, cases, and proportion 
result = pd.DataFrame({
    "MONTH": monthly_counts.index,
    "CASES in 2013": monthly_counts.values,
    "Percent_of_Total": percentages.values})

result

    MONTH CASES in 2013 Percent_of_Total
0       1           269         8.080505
1       2           234         7.029138
2       3           218         6.548513
3       4           267         8.020427
4       5           366        10.994293
5       6           285         8.561129
6       7           287         8.621208
7       8           284          8.53109
8       9           234         7.029138
9      10           293         8.801442
10     11           323         9.702613
11     12           269         8.080505

In [71]:
# KERN COUNTY MONTHLY CASES ------------------------------

kern_data = (result["Percent_of_Total"] * .01) * 1659
kern_data

0     134.055572
1     116.613397
2     108.639832
3     133.058877
4     182.395314
5     142.029138
6     143.025834
7      141.53079
8     116.613397
9     146.015921
10    160.966356
11    134.055572
Name: Percent_of_Total, dtype: object

In [72]:
# LOS ANGELES COUNTY MONTHLY CASES ---------------------

la_data = (result["Percent_of_Total"] * .01) * 338
la_data

0     27.312106
1     23.758486
2     22.133974
3     27.109042
4     37.160709
5     28.936618
6     29.139682
7     28.835086
8     23.758486
9     29.748874
10    32.794833
11    27.312106
Name: Percent_of_Total, dtype: object

In [73]:
# RIVERSIDE COUNTY MONTHLY CASES ---------------------

riverside_data = (result["Percent_of_Total"] * .01) * 34
riverside_data

0     2.747372
1     2.389907
2     2.226494
3     2.726945
4     3.738059
5     2.910784
6     2.931211
7     2.900571
8     2.389907
9      2.99249
10    3.298889
11    2.747372
Name: Percent_of_Total, dtype: object

In [77]:
# SAN DIEGO COUNTY MONTHLY CASES ---------------------

sd_data = (result["Percent_of_Total"] * .01) * 93
sd_data

0      7.514869
1      6.537098
2      6.090117
3      7.458997
4     10.224692
5       7.96185
6      8.017723
7      7.933914
8      6.537098
9      8.185341
10      9.02343
11     7.514869
Name: Percent_of_Total, dtype: object

In [75]:
# SAN JOAQUIN COUNTY MONTHLY CASES ---------------------

sj_data = (result["Percent_of_Total"] * .01) * 51
sj_data

0     4.121057
1      3.58486
2     3.339742
3     4.090418
4     5.607089
5     4.366176
6     4.396816
7     4.350856
8      3.58486
9     4.488735
10    4.948333
11    4.121057
Name: Percent_of_Total, dtype: object

In [76]:
# TULARE COUNTY MONTHLY CASES ---------------------

tulare_data = (result["Percent_of_Total"] * .01) * 116
tulare_data

0      9.373385
1        8.1538
2      7.596275
3      9.303695
4     12.753379
5       9.93091
6     10.000601
7      9.896065
8        8.1538
9     10.209673
10    11.255032
11     9.373385
Name: Percent_of_Total, dtype: object